### ISSUE TITLE
Develop Maintenance Functions for Rail & Bus

### ISSUE THREAD

**Issue by brichard1638** [kiernann/metro#14]
Great R package! It is believed to be critical to include a few functions that capture the maintenance schedules in real time for both rail and buses.

If machine learning is to be applied to rail and bus incidents, it would add a wonderful dimension to the accuracy of the prediction if maintenance schedules were also included.

For example, bus_maint and rail_maint functions could capture the work that is being done.

Perhaps a set of functions related to the future of planned maintenance work could also be included. Functions such as bus_maint_fut and rail_maint_fut come to mind.

**Comment by k5cents** [comment]
I agree this would be cool to have! I don't think I see any such information as an [available API endpoint](https://developer.wmata.com/docs/services/), but if you know where to find that information then I could definitely work them into a function for this package.

**Comment by brichard1638** [comment]
I didn't see the functionality either which is why I was reaching out to make the suggestion.

The more granular the API is, the better the information will be.

If you can do anything to move the needle on this, that would be great!

Brice
________________________________

**Comment by k5cents** [comment]
Sorry but this is an unofficial 3rd party interface to the API developed by WMATA. I have no input over what functionality the API provides, I just make the tools that read it into R.

I'd reach out to WMATA directly with your idea: https://developer.wmata.com/
